const data = {
  products: [
    {
      name: `Premium Men's T-Shirt`,
      slug: 'premium-men-tshirt',
      category: 'Shirts',
      image: '/shirts/1.jpg',
      amount: 70,
      brand: 'Gucci',
      rating: 4.5,
      numReviews: 8,
      countInStock: 40,
      description: 'A popular shirt',
    },
    {
      name: `Premium Women's T-Shirt`,
      slug: 'premium-women-tshirt',
      category: 'Shirts',
      image: '/shirts/2.jpg',
      amount: 80,
      brand: 'Gucci',
      rating: 3.2,
      numReviews: 10,
      countInStock: 30,
      description: 'A popular shirt',
    },
    {
      name: `Winter Jacker`,
      slug: 'winter-jacket',
      category: 'Shirts',
      image: '/shirts/3.jpg',
      amount: 58,
      brand: 'Raymond Stores',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: `Turkey Packet Shirt`,
      slug: 'turkey-packet-shirt',
      category: 'Shirts',
      image: '/shirts/4.jpg',
      amount: 90,
      brand: 'Turkey',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: 'Turkey Packet Shirt premium',
    },
    {
      name: `Vintage Men's T-Shirt`,
      slug: 'vintage-men-t-shirt',
      category: 'Shirts',
      image: '/shirts/5.jpg',
      amount: 195,
      brand: 'Zara',
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: 'Vintage Mens T-Shirt',
    },
    {
      name: `Sports Men's Shirt`,
      slug: 'sports-men-shirt',
      category: 'Shirts',
      image: '/shirts/6.jpg',
      amount: 45,
      brand: 'Versace',
      rating: 4.4,
      numReviews: 14,
      countInStock: 120,
      description: 'Sports Men Shirt',
    },
    {
      name: `Nike Leather Juggers`,
      slug: 'nike-leather-juggers',
      category: 'Shoes',
      image: '/shoes/1.jpg',
      amount: 85,
      brand: 'Nike',
      rating: 4.4,
      numReviews: 14,
      countInStock: 120,
      description: 'Nike Sports Juggers',
    },
    {
      name: `Men's Sports Trainers`,
      slug: 'men-sports-trainers',
      category: 'Shoes',
      image: '/shoes/2.jpg',
      amount: 75,
      brand: 'Nike',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'Mens Sports Trainers',
    },
    {
      name: 'Geniun Leather Snickers',
      slug: 'geniun-leather-snickers',
      category: 'Shoes',
      image: '/shoes/3.jpg',
      amount: 45,
      brand: 'Gucci',
      rating: 3.4,
      numReviews: 14,
      countInStock: 80,
      description: 'Geniun Leather Snickers',
    },
    {
      name: 'New Arrival Shoe',
      slug: 'new-arrival-shoe',
      category: 'Shoes',
      image: '/shoes/4.jpg',
      amount: 55,
      brand: 'Spencer',
      rating: 2.5,
      numReviews: 14,
      countInStock: 90,
      description: 'New Arrival Shoe',
    },
    {
      name: 'Exercise Men Shoe',
      slug: 'exercise-men-shoe',
      category: 'Shoes',
      image: '/shoes/5.jpg',
      amount: 75,
      brand: 'Gabbana',
      rating: 2.4,
      numReviews: 14,
      countInStock: 190,
      description: 'Best Exercise Men Shoe',
    },
    {
      name: 'Young Pal Leather Shoes',
      slug: 'young-pal-leather-shoe',
      category: 'Shoes',
      image: '/shoes/6.jpg',
      amount: 45,
      brand: 'Gucci',
      rating: 2.8,
      numReviews: 14,
      countInStock: 50,
      description: 'Young Pal Leather Shoe',
    },
  ],
};

export default data;
