import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.coma',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: `Premium Men's T-Shirt`,
      slug: 'premium-men-tshirt',
      category: 'Shirts',
      image: '/shirts/1.jpg',
      amount: 70.29,
      brand: 'Gucci',
      rating: 4.5,
      numReviews: 8,
      countInStock: 0,
      description:
        'Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
      name: `Premium Women's T-Shirt`,
      slug: 'premium-women-tshirt',
      category: 'Shirts',
      image: '/shirts/2.jpg',
      amount: 80.29,
      brand: 'Gucci',
      rating: 3.2,
      numReviews: 10,
      countInStock: 30,
      description:
        'Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
      name: `Winter Jacker`,
      slug: 'winter-jacket',
      category: 'Shirts',
      image: '/shirts/3.jpg',
      amount: 58.3,
      brand: 'Raymond Stores',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description:
        'Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
      name: `Turkey Packet Shirt`,
      slug: 'turkey-packet-shirt',
      category: 'Shirts',
      image: '/shirts/4.jpg',
      amount: 90.32,
      brand: 'Turkey',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description:
        'Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
      name: `Vintage Men's T-Shirt`,
      slug: 'vintage-men-t-shirt',
      category: 'Shirts',
      image: '/shirts/5.jpg',
      amount: 195.12,
      brand: 'Zara',
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description:
        'Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
      name: `Sports Men's Shirt`,
      slug: 'sports-men-shirt',
      category: 'Shirts',
      image: '/shirts/6.jpg',
      amount: 45.1,
      brand: 'Versace',
      rating: 4.4,
      numReviews: 14,
      countInStock: 120,
      description:
        'Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
      name: `Nike Leather Juggers`,
      slug: 'nike-leather-juggers',
      category: 'Shoes',
      image: '/shoes/1.jpg',
      amount: 85.29,
      brand: 'Nike',
      rating: 4.4,
      numReviews: 14,
      countInStock: 120,
      description:
        'Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
      name: `Men Sports Trainers`,
      slug: 'men-sports-trainers',
      category: 'Shoes',
      image: '/shoes/2.jpg',
      amount: 75.13,
      brand: 'Nike',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description:
        'Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
      name: 'Geniun Leather Snickers',
      slug: 'geniun-leather-snickers',
      category: 'Shoes',
      image: '/shoes/3.jpg',
      amount: 45.8,
      brand: 'Gucci',
      rating: 3.4,
      numReviews: 14,
      countInStock: 80,
      description:
        'Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
      name: 'New Arrival Shoe',
      slug: 'new-arrival-shoe',
      category: 'Shoes',
      image: '/shoes/4.jpg',
      amount: 55.76,
      brand: 'Spencer',
      rating: 2.5,
      numReviews: 14,
      countInStock: 90,
      description:
        'Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
      name: 'Exercise Men Shoe',
      slug: 'exercise-men-shoe',
      category: 'Shoes',
      image: '/shoes/5.jpg',
      amount: 75.43,
      brand: 'Gabbana',
      rating: 2.4,
      numReviews: 14,
      countInStock: 190,
      description:
        'Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
      name: 'Young Pal Leather Shoes',
      slug: 'young-pal-leather-shoe',
      category: 'Shoes',
      image: '/shoes/6.jpg',
      amount: 45.02,
      brand: 'Gucci',
      rating: 2.8,
      numReviews: 14,
      countInStock: 50,
      description:
        'Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
  ],
};

export default data;
